# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.


s = "CCACTATGGCAGGCGATCCCTATGCCGCATAGTAGAATGATGACGCCTCGCAAGAGCACCCCGCCGAGCTGAGCGTGATACATACCAAAAACGTCCGAGAGCGTGGTCAAAGTGTGCCGAATGTACGCTGCCCCGTTCTACTCTCAGGGGACTAGTTTGATCCCTGGCGGCGCTGGGGGTCTCCCGTACGTCGCGAGGCCTCGGATAGTGTGCGCACGAGCTGCATGAAAAGCCCACATAAATTTTCTCGGTACCTCAGATTCAGCGGAACTCCCCCAGCACGTGAGAGCATATCAGTAGGGTTGCAGTAAGCACAGAGTTGAAAACCCGCGCGCCCACGTGGTGACAGTATAAGGTGATATGAGGACCGGAGCGTACCTTCCTTATCTGCACAAACAGTGAACTCTGTTGTGCGACCTAGCTTCCAGCCGCGGCCGGCATCTGCCGGATGCCAGTGCCTCAAGGCACATGACAAAAAAAAATCAATTTGCGGGATGCAGACATGGTCGGGTTTGTGGCCCTTGCCTTTCTGTAGGTCGAATCGTGATCAAATCTCTACTCTATTGTTACTTGGGCGCTGTATCGTCCGTCTTTTGGGCGTTATTAGGATCCCGTTGCTCTCCAATTTTCGAATTACGATGCCGACGTGTGTTGTGTGAAGACACCGGTCTTCTAGGAATAAACTCAGACAAAAATACTATTCAAGGCACGAAGCTGAACATCGCCGGTGGAATCAGATGTGCGCGTAGCCATCCATTGCCGAGCTCAACCTCACAACATGGATTGTATGGACACGTATTAAGATACGGTTGCAATAGCTGGTAGGAATGGGTACGCCCTGGACCTGACGTCGATACAGGATTGAGCGTCCAAGCTCTGATGGGCGCATTCAATTCACAGGCTGGCGGCGGCCTGAGTTCCCGCGCCGTATTTTCCCCCCTGTCTTGGATAGGATTACTGCCTCCCAATTCGATTAAAACGGTATCTGGCACCCCC"

# base counter

A = 0
T = 0
C = 0
G = 0

for x in s:
    if x == 'A':
        A += 1
    elif x == 'T':
        T += 1
    elif x == 'C':
        C += 1
    else:
        G += 1
print(str(A) + ' ' + str(C) + ' ' + str(G) + ' ' + str(T))